src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin

from authentication import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomeView.as_view(), name="home"),
    url(r'^login$', views.LoginView.as_view(), name="login"),
    url(r'^logout$', views.LogoutView.as_view(), name="logout"),

    # Social Auth
    url(r'', include('social_django.urls', namespace='social')),

    url(r'^martor/', include('martor.urls')),

    # define sub module url routing
    url(r'^auth/', include('authentication.url', namespace="auth")),
    url(r'^course/', include('course.url', namespace="course")),
    url(r'^task/', include('task.url', namespace="task")),
    url(r'^category/', include('prerequisite.url', namespace="prerequisite")),
    url(r'^profile/', include('user_profile.url', namespace="profile")),
    url(r'^desk/', include('desk.url', namespace="desk")),
    url(r'^catalog/', include('catalog.url', namespace="catalog")),
    url(r'^administration/', include('administration.url', namespace="administration")),
    url(r'^chat/', include('chat.url', namespace="chat")),

    # Avatar urls
    url(r'^avatar/', include('avatar.urls')),
    url(r'^media/avatars/', include('avatar.urls')),
]


if settings.DEBUG:  # pragma: no cover
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    # this is needed to load static files during development
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    # this is needed to load the media files during development
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/authentication/models.py
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
import itertools
from django.template.defaultfilters import slugify


class User(AbstractUser):
    verifyEmailToken = models.CharField(max_length=100, null=True)
    verifyEmailTokenExpireDate = models.DateTimeField(null=True)
    can_be_instructor = models.BooleanField(
        _('Instructor'), default=settings.USER_ABLE_TO_BECOME_INSTRUCTOR)
    has_email_notifications_activated = models.BooleanField(_('Email notifications'),
                                                            default=True)

    @classmethod
    def get_user_by_email(cls, email):
        for user in User.objects.filter(email=email):
            return user
        raise ObjectDoesNotExist

    @classmethod
    def get_user_by_token(cls, token):
        for user in User.objects.filter(verifyEmailToken=token):
            return user
        raise ObjectDoesNotExist

    @classmethod
    def check_email_already_registered(cls, email):
        tmp = False
        for user in User.objects.filter(email=email):
            if user.email == email:
                tmp = True
        return tmp


class Event(models.Model):
    start_date = models.DateField(null=True)
    end_date = models.DateField(null=True)
    institution = models.CharField(max_length=200, null=True)
    position = models.CharField(max_length=200, null=True)
    user = models.ForeignKey(User, verbose_name=_('user'),
                             related_name='events', on_delete=models.CASCADE, null=True)
    slug = models.SlugField(max_length=140, unique=True)

    # user + position + institution is unique to avoid duplicates
    class Meta:
        unique_together = ('user', 'institution', 'position',)

    def __str__(self):
        return '{0} - {1} - {2}'.format(self.user.username, self.institution, self.position)

    def save(self, *args, **kwargs):
        if not self.id or self.slug is None:
            self.slug = orig = slugify('%s %s %s' % (
                self.user.username, self.institution, self.position))

            for x in itertools.count(1):
                if not Event.objects.filter(slug=self.slug).exists():
                    break
                self.slug = '%s-%d' % (orig, x)

        super(Event, self).save(*args, **kwargs)


class Specialty(models.Model):
    title = models.CharField(max_length=200, null=False)

    KNOWLEDGE_LEVEL_CHOICES = (
        ('1', _('Novice')),
        ('2', _('Adept')),
        ('3', _('Master')),
    )
    knowledge_level = models.CharField(
        _('Knowledge level'), max_length=1, choices=KNOWLEDGE_LEVEL_CHOICES)

    user = models.ForeignKey(User, verbose_name=_('user'),
                             related_name='specialties',
                             on_delete=models.CASCADE, null=True)
    slug = models.SlugField(max_length=140, unique=True)

    class Meta:
        verbose_name_plural = "specialties"

    def __str__(self):
        return '{}'.format(self.title)

    def save(self, *args, **kwargs):
        if not self.id or self.slug is None:
            self.slug = orig = slugify(self.title)

            for x in itertools.count(1):
                if not Specialty.objects.filter(slug=self.slug).exists():
                    break
                self.slug = '%s-%d' % (orig, x)

        super(Specialty, self).save(*args, **kwargs)

src/course/models.py
import itertools
from django.template.defaultfilters import slugify
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.validators import MaxValueValidator, MinValueValidator

from task.models import TaskBase

User = get_user_model()


class Course(models.Model):
    name = models.CharField(_('Name'), max_length=55)
    short_description = models.CharField(_('Short description'), max_length=166)
    long_description = models.TextField(_('Long description'))
    COURSE_LANGUAGE_CHOICES = (
        ('no', '--------'),
        ('en', 'English'),
        ('de', 'Deutsch'),
        ('fr', 'Français'),
    )
    course_language = models.CharField(
        _('Course language'), max_length=2, choices=COURSE_LANGUAGE_CHOICES, default='no')
    # needed effort in minutes
    effort = models.PositiveIntegerField(_('Effort'), )
    # flag that says whether or not the course is available for users
    published = models.BooleanField(_('Published'), default=False)
    participants = models.ManyToManyField(User, through='Participant', related_name='participants')
    instructors = models.ManyToManyField(User, through='Instructor', related_name='instructors')
    picture = models.ImageField(_('Picture'), upload_to='course_images/',
                                blank=True)
    slug = models.SlugField(max_length=140, unique=True)

    def getPicture(self):
        if not self.picture:
            # depending on your template
            self.picture = '../static/img/Course.jpg'
        return self.picture.url

    def __str__(self):
        return '{}'.format(self.name)

    def save(self, *args, **kwargs):
        if not self.id or self.slug is None:
            self.slug = orig = slugify(self.name)

            for x in itertools.count(1):
                if not Course.objects.filter(slug=self.slug).exists():
                    break
                self.slug = '%s-%d' % (orig, x)

        super(Course, self).save(*args, **kwargs)


class Instructor(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    course = models.ForeignKey(Course, on_delete=models.DO_NOTHING)

    # user + course is unique to avoid duplicates
    class Meta:
        unique_together = ('user', 'course',)
        auto_created = True

    def __str__(self):
        return '{} - {}'.format(self.course, self.user)


class Participant(models.Model):
    # a user can rate a course only once
    # rating = 0 -> user hasn't rated yet for that course
    # rating > 0 -> user rated for that course
    rating = models.PositiveIntegerField(
        _('Rating'),
        validators=[MaxValueValidator(5), MinValueValidator(0)]
    )
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    course = models.ForeignKey(Course, on_delete=models.DO_NOTHING)

    # useris + course is unique so that the user can only rate and join the course once
    class Meta:
        unique_together = ('user', 'course',)

    def __str__(self):
        return '{} - {}'.format(self.course, self.user)


class Lesson(models.Model):
    # name of the lesson
    name = models.CharField(_('Name'), max_length=100)
    # the position of the lesson amongst the other lessons
    position = models.PositiveIntegerField(_('Position'))
    # FK to course
    course = models.ForeignKey(Course, verbose_name=_('Course'),
                               related_name='lessons', on_delete=models.CASCADE)
    slug = models.SlugField(max_length=140, unique=True)

    def __str__(self):
        return '{}'.format(self.name)

    def save(self, *args, **kwargs):
        if not self.id or self.slug is None:
            self.slug = orig = slugify(self.name)

            for x in itertools.count(1):
                if not Lesson.objects.filter(slug=self.slug).exists():
                    break
                self.slug = '%s-%d' % (orig, x)

        if self.position is None:
            last_lesson = Lesson.objects.filter(
                course_id=self.course.id).order_by('-position').first()
            if last_lesson is None:
                self.position = 0
            else:
                self.position = last_lesson.position + 1

        super(Lesson, self).save(*args, **kwargs)

    @classmethod
    def get_all_lessons(cls):
        return cls.objects.all()

    def get_related_tasks(self):
        tasks = TaskBase.objects.select_related(
            'programmingexercise', 'exercise', 'text', 'video', 'quiz').filter(lesson=self)
        return tasks

src/administration/views/course.py
import json

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseServerError
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.utils.translation import ugettext as _
from django.views.generic import DetailView, CreateView, UpdateView, ListView
from django.views.generic.base import View

from authentication.models import User
from course.forms import CourseCreateForm
from course.models import Course, Instructor
from course.views import InstructorRequiredMixin
from prerequisite.forms import CategoryAjaxCreateForm
from task.models import TaskBase


class CourseDetailView(LoginRequiredMixin, InstructorRequiredMixin, DetailView):
    model = Course
    template_name = 'administration/course/detail.html'
    slug_url_kwarg = 'course_slug'
    context_object_name = 'course'


class CoursesView(LoginRequiredMixin, InstructorRequiredMixin, ListView):
    model = Course
    template_name = 'administration/course/courses.html'

    def get_queryset(self):

        instructors = Instructor.objects.filter(user=self.request.user)
        course_pks = []
        for instructor in instructors:
            course_pks.append(instructor.course.pk)

        return Course.objects.filter(pk__in=course_pks)


class CourseCreateView(InstructorRequiredMixin, LoginRequiredMixin, CreateView):
    form_class = CourseCreateForm
    template_name = 'administration/course/create.html'

    def get_context_data(self, **kwargs):
        context = super(CourseCreateView, self).get_context_data()
        context['category_form'] = CategoryAjaxCreateForm()
        return context

    def form_valid(self, form):
        response = super(CourseCreateView, self).form_valid(form)

        categories = form.cleaned_data['categories']
        if categories.count() > 0:
            self.object.categories.set(categories)

        prerequisites = form.cleaned_data['prerequisites']
        if prerequisites.count() > 0:
            self.object.prerequisites.set(prerequisites)

        new_instructors = form.cleaned_data['instructors']
        if new_instructors.count() > 0:
            self.object.instructors.set(new_instructors)

        messages.success(
            self.request,
            _("%(course)s created successfully") % {'course': self.object}
        )
        return response

    def get_success_url(self):
        return reverse('administration:course_detail', kwargs={'course_slug': self.object.slug})


class CourseUpdateView(LoginRequiredMixin, InstructorRequiredMixin, UpdateView):
    model = Course
    form_class = CourseCreateForm
    template_name = 'administration/course/update.html'

    def get_context_data(self, **kwargs):
        context = super(CourseUpdateView, self).get_context_data()
        context['category_form'] = CategoryAjaxCreateForm()
        return context

    def form_valid(self, form):
        response = super(CourseUpdateView, self).form_valid(form)

        new_cats = form.cleaned_data['categories']
        if new_cats.count() > 0:
            self.object.categories.set(new_cats)

        new_prerequisites = form.cleaned_data['prerequisites']
        if new_prerequisites.count() > 0:
            self.object.prerequisites.set(new_prerequisites)

        new_instructors = form.cleaned_data['instructors']
        if new_instructors.count() > 0:
            self.object.instructors.set(new_instructors)

        messages.success(
            self.request,
            _("%(course)s updated successfully") % {'course': self.object}
        )
        return response

    def get_object(self):
        object = get_object_or_404(Course, slug=self.kwargs['course_slug'])
        return object

    def get_success_url(self):
        return reverse('administration:course_detail', kwargs={'course_slug': self.object.slug})


class CourseInstructorDetailView(LoginRequiredMixin, DetailView):
    context_object_name = 'course_list'
    template_name = 'administration/course/instructor_detail.html'
    queryset = Course.objects.all()
    slug_url_kwarg = 'course_slug'

    def get_context_data(self, **kwargs):
        context = super(CourseInstructorDetailView, self).get_context_data(**kwargs)
        user = User.objects.filter(username=self.kwargs['instructor_slug']).first()
        recent_course = Course.objects.filter(slug=self.kwargs['course_slug']).first()

        context['user'] = user
        context['events'] = user.events.all()
        context['specialties'] = user.specialties.order_by('-knowledge_level').all()
        related_instructors = Instructor.objects.filter(user=user.id).all()

        courses = list()
        for related in related_instructors:
            courses.append(Course.objects.filter(id=related.course_id).first())
        context['courses'] = courses
        context['recent_course'] = recent_course
        return context


class CoursePublishUnpublishView(LoginRequiredMixin, InstructorRequiredMixin, View):
    model = Course

    def post(self, request, course_slug):
        course = get_object_or_404(Course, slug=course_slug)

        if course.published:  # unpublish
            course.published = False
            self.__add_message(_('The course %(name)s was successfully unpublished'), course)
        else:  # publish
            course.published = True
            self.__add_message(_('The course %(name)s was successfully published'), course)
        course.save()

        return redirect('administration:courses')

    def __add_message(self, message, course):
        messages.add_message(self.request, messages.SUCCESS, _(
            message % {'name': course.name}))


class CourseUpdateStructureView(LoginRequiredMixin, InstructorRequiredMixin, View):
    def post(self, request, course_slug):
        course = get_object_or_404(Course, slug=course_slug)
        json_as_string = request.POST.get("structure", "")
        if json_as_string.strip() == "":
            return HttpResponse(status=201)
        data = json.loads(json_as_string)

        lessons = data[0]

        lesson_counter = 0
        task_counter = 0

        for lesson in lessons:
            lesson_entity = course.lessons.filter(id=lesson["id"]).first()
            if lesson_entity is None:
                return HttpResponseServerError()
            lesson_entity.position = lesson_counter
            lesson_counter = lesson_counter + 1
            lesson_entity.save()

            for task in lesson["children"][0]:
                task = TaskBase.objects.filter(id=task["id"]).first()
                if task is None:
                    return HttpResponseServerError()
                task.lesson = lesson_entity
                task.position = task_counter
                task_counter = task_counter + 1
                task.save()
            task_counter = 0

        return HttpResponse(_("The update of the course structure was successfully"), status=200)

src/templates/catalog/course_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load avatar_tags %}
{% load url_helper %}

{% block heading %}{% trans "Catalog - Course" %} {{ course.name }}{% endblock %}

{% block content %}
{% if course.published %}
    <div class="row">
      <div class="col-lg-12">
        <p>{{ course.short_description }}</p>
        <hr>
        {% if authenticated == True %}
          {% if participate == False %}
          <form method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="{% trans "Enter" %}"/>
          </form>
          {% else %}
            <p>{% trans "You are a member of this course" %}</p>
            <a class="btn btn-primary" href="{%  url 'course:continue' course_slug=course.slug %}">{% trans 'Start' %}</a>
          {%  endif %}
        {%  endif %}
      </div>
    </div>

    <div class="row">
      <div class="col-sm"></div>
      <div class="col-lg-12">
        <hr>
        <p>{{ course.long_description }}</p>
      </div>
      <div class="col-sm"></div>
    </div>
    <div class="row course-detail">
      <div class="col-sm"></div>
      <div class="col-lg-12">
        <hr>
        <p>Lessons:</p>
        <div class="list-group">
        {% for lesson in course.lessons.all|dictsort:"position" %}

            <p href="#details_{{ lesson.slug }}" class="list-group-item" data-toggle="collapse" aria-expanded="false">
              <svg-icon class="nav-glyph toggle right"><src href="{% static 'svg/si-glyph-arrow-right.svg' %}"/></svg-icon>
              <svg-icon class="nav-glyph toggle down"><src href="{% static 'svg/si-glyph-arrow-down.svg' %}"/></svg-icon>
              {% blocktrans with lesson_name=lesson.name %}{{ lesson_name }}{% endblocktrans %}
            </p>
            <div class="list-group collapse" id="details_{{ lesson.slug }}">


                {% for task in lesson.get_related_tasks.all|dictsort:"position" %}
                  <p class="list-group-item">
                    {% blocktrans with task_name=task.name %}{{ task_name }}{% endblocktrans %}
                  </p>
                {% endfor %}

            </div>

        {% endfor %}
        </div>
      </div>
      <div class="col-sm"></div>
    </div>
    <div class="row">
      <div class="col-sm"></div>
      <div class="col-lg-12">
        <hr>
        <div class="row">
      <div class="col-md-3">
        <ul class="list-group">
          <li class="list-group-item"><p>{% blocktrans with language=course.get_course_language_display %}Language: {{ language }}{% endblocktrans %}</p></li>
          <li class="list-group-item"><p>{% blocktrans with effort=course.effort %}Effort: {{ effort }} minutes{% endblocktrans %}</p></li>
        </ul>
      </div>
      <div class="col-md-9">
        <ul class="list-group">
          <li class="list-group-item">
            <ul class="list-inline">
              <li class="list-inline-item"><p>{% trans "Category:" %}</p></li>
              {% for category in course.categories.all %}
                <li class="list-inline-item">{{ category }}</li>
              {% endfor %}
            </ul>
          </li>
          <li class="list-group-item">
            <ul class="list-inline">
              <li class="list-inline-item"><p>Previous knowledge:</p></li>
              {% for prerequisite in course.prerequisites.all %}
                <li class="list-inline-item">{{ prerequisite }}</li>
              {% endfor %}
            </ul>
          </li>
        </ul>
      </div>
    </div></div>
      <div class="col-sm"></div>
    </div>
    <div class="row">
      <div class="col-sm"></div>
      <div class="col-lg-12">
        <hr>
        <ul class="list-inline">
          <li class="list-inline-item">{% trans "Trainer:" %}</li>
          {% for instructor in course.instructors.all %}
          <li class="list-inline-item">
            <a href="{%  url 'catalog:instructor_detail' course_slug=course.slug instructor_slug=instructor.username %}" class="details">
              {% avatar instructor 40 class="mx-auto rounded-circle"%} {{ instructor }}
            </a>
          </li>
          {% endfor %}
        </ul>
      </div>
      <div class="col-sm"></div>
    </div>

{% endif %}
{% endblock %}
{% block js %}
<script src="{% static 'javascript/course_detail.js' %}"></script>
{% endblock %}

src/templates/catalog/courses.html
{% extends "base.html" %}
{% load i18n %}
{% load custom_tags %}
{% load crispy_forms_tags %}


{% block heading %}{% trans "Course Catalog" %}{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <form action="{% url 'catalog:courses' %}" method="get" class="search-form">
                {% csrf_token %}
                <div class="row my-form-inline">
                    <div class="col-md-6 col-lg-auto">
                        {{ form.q|as_crispy_field }}
                    </div>
                     <div class="col-md-6 col-lg-auto">
                        {{ form.categories|as_crispy_field }}
                    </div>
                     <div class="col-md-6 col-lg-auto">
                        {{ form.languages|as_crispy_field }}
                    </div>
                    <div class="col-md-6 col-lg-auto search-button">
                        <input type="submit" class="btn btn-primary" value="{% trans "Search" %}"/>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <hr>
    <div class="row">
        {% for course in object_list %}
            <div class="col-md-4 mb-3">
                <div class="course card text-center">
                    <div class="card-img-container">
                        <div style="background-image:url({{ course.getPicture}})" class="image-box mx-auto d-block img-fluid card-img-top" title="Title image of a course"></div>
                    </div>

                    <div class="card-body">
                        <div class="card-text">
                            <h4 class="card-title">
                            {{ course.name }}
                            </h4>

                            <p class="card-content">{{ course.short_description }}</p>
                        </div>
                        <div class="body-buttons">
                            <div class="row">
                                <div class="col-6 mx-auto text-left">
                                    {% if request.user.is_authenticated %}
                                    <form action="{% url 'catalog:courses' %}" method="post">
                                        <input hidden name="course_slug" value="{{ course.slug }}">
                                        {% get_action course participants as action%}
                                        <input hidden name="action"
                                               value="{{ action }}">
                                        {% csrf_token %}
                                        <input type="submit" class="btn {% if action == 'enter' %}btn-primary{% else %}btn-secondary{% endif %}"
                                               value="{% get_action_name course participants %}"/>
                                    </form>
                                {% endif %}
                                </div>
                                <div class="{% if request.user.is_authenticated %}col-6 text-right{% else %}col-12 text-center{% endif %}">
                                    <a href="{% url 'catalog:course_detail' course_slug=course.slug %}"
                                       class="details btn btn-primary">{% trans 'Details' %}</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="col-md-12">
            <p>{% trans 'No courses available.' %}</p>
            </div>
        {% endfor %}
    </div>

{% endblock %}

src/templates/catalog/instructor_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load avatar_tags %}


{% block js %}
<script type="text/javascript" src="{% static 'plugins/js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/course/course_detail.js' %}"></script>
{% endblock %}

{% load url_helper %}

{% block heading %}
    {% trans "Instructor " %}{%blocktrans with username=instructor.username%}{{username}}{%endblocktrans%}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-3">
                {% avatar instructor 235 class="mx-auto rounded-circle styled-avatar"%}
    </div>
    <div class="col-md-9">
        <table class="table">
            <tr>
                <th>{% trans "Username: " %}</th>
                <td>{%blocktrans with username=instructor.username%}{{username}}{%endblocktrans%}</td>
                <td></td>
            </tr>
            <tr>
                <th>{% trans "Name: "%}</th>
                <td>
                    {%blocktrans with first_name=instructor.first_name%}{{first_name}}{%endblocktrans%}
                    {% blocktrans with last_name=instructor.last_name %} {{last_name}}{% endblocktrans %}
                </td>
            </tr>
            <tr>
                <th>{% trans "Email: "%}</th>
                <td>{% blocktrans with email=instructor.email %} {{email}}{% endblocktrans %}</td>
            </tr>
        </table>
    </div>
</div>


<h3>{% trans "Biography"%}</h3>
<div class="row">
    <div class="col-md-12">
        <table class="table">
            <thead>
                <tr>
                    <th>{% trans "Position: " %}</th>
                    <th>{% trans "Institution: "%}</th>
                    <th>{% trans "From: "%}</th>
                    <th>{% trans "To: "%}</th>
                </tr>

            </thead>
              {% for event in instructor.events.all|dictsort:"start_date"%}
            <tbody>
                <tr>
                    <td>{%blocktrans with position=event.position%}{{position}}{%endblocktrans%}</td>
                    <td>{%blocktrans with institution=event.institution%}{{institution}}{%endblocktrans%}</td>
                    <td>{%blocktrans with from=event.start_date%}{{from}}{%endblocktrans%}</td>
                    <td>{%blocktrans with to=event.end_date%}{{to}}{%endblocktrans%}</td>
                </tr>
            </tbody>

          {% endfor%}
        </table>
    </div>
</div>


<h3>{% trans "Specialties"%}</h3>
<div class="row">
    <div class="col-md-12">
        <table class="table">
            <thead>
                <tr>
                    <th>{% trans "Title: " %}</th>
                    <th>{% trans "Knowledge level: "%}</th>
                </tr>
            </thead>
              {% for specialty in instructor.specialties.all|dictsortreversed:"knowledge_level"%}
            <tbody>
            <tr>
               <td>{%blocktrans with title=specialty.title%}{{title}}{%endblocktrans%}</td>
                <td>{%blocktrans with knowledge_level=specialty.get_knowledge_level_display%}{{knowledge_level}}{%endblocktrans%}</td>
            </tr>
            </tbody>
        {% endfor%}
        </table>

    </div>
</div>


<h3>{% trans "Courses of the same instructor "%}</h3>

<div class="row">
    <div class="col-12">
      <!-- Course History or Most Recent Actovoties-->
      <hr>
    </div>
      {% for course in courses %}
        <div class="col-12 mt-3">
            <h4>{{ course.name }}</h4>
            <p>{{ course.short_description }}</p>
            <a class="btn btn-secondary enough-space-down" href="{%  url 'administration:course_detail' course_slug=course.slug %}" class="details">{% trans 'Details' %}</a>
        </div>
      {% empty %}
          <div class="col-12">
            <p>{% trans 'No courses available.' %}</p>
          </div>
      {% endfor %}
</div>
<div class="row">
    <div class="col-md-12">
        <hr>
        <a class="btn btn-primary enough-space-down" href="{{ request.META.HTTP_REFERER }}" class="details">
              {% trans "Back " %}
        </a>
    </div>
</div>
{% endblock %}